### ISSUE TITLE
slideshare downloader had error

### ISSUE THREAD

**Issue by Jamesxxx1997** [officialpm/Slideshare-Downloader#111]
Hi!  I found couldn't download any files with this downloader, can you take it a look? Thank you.
<img width="872" alt="CleanShot 2022-02-11 at 11 13 13@2x" src="https://user-images.githubusercontent.com/29252582/153532364-bae32415-7fd9-44a4-9023-ec59bb9d711a.png">

**Comment by officialpm** [comment]
Fixed!

Please check and star the repo if it worked for you? 👍🏻

**Comment by Jamesxxx1997** [comment]
I've test some links, still don't work :(
screen record : https://www.loom.com/share/99ff5eaebf9244b78aac78820fb6e13b

**Comment by officialpm** [comment]
Please use this link - https://slideshare.vercel.app/
