### ISSUE TITLE
the site isn't working

### ISSUE THREAD

**Issue by ShadowDrifterII** [officialpm/Slideshare-Downloader#92]
2 days of "Some server error occured. Please try again later."

**Comment by officialpm** [comment]
Fixed :)

**Comment by VarunS2002** [comment]
@officialpm 
It is still happening man :(
![image](https://user-images.githubusercontent.com/30069380/131221260-b3046b01-96c2-4ec2-bbc0-c452b7e0afe3.png)
Console
![image](https://user-images.githubusercontent.com/30069380/131221265-e10d5b66-ced2-4bc9-82d5-d292f68cdf1e.png)

**Comment by Symbian9** [comment]
Same again: *"Some server error occured. Please try again later"*

**Comment by officialpm** [comment]
> Same again: _"Some server error occured. Please try again later"_

Please try again. Thank you for informing me.

**Comment by Symbian9** [comment]
> Please try again. Thank you for informing me.

Nope. Just tried and still does NOT work:

- https://officialpm.github.io/Slideshare-Downloader/

**Comment by officialpm** [comment]
> > Please try again. Thank you for informing me.
> 
> Just tried and still does NOT work:
> 
> * https://officialpm.github.io/Slideshare-Downloader/

Fixed!

Please check and star the repo if it worked for you? 👍🏻

**Comment by Symbian9** [comment]
> Fixed!
>
> Please check and star the repo if it worked for you? 👍🏻

@officialpm, Nope, it does not work...

![Screenshot_2022-02-14_01-41-14](https://user-images.githubusercontent.com/13188580/153780663-57744551-2469-4d22-9d37-7733fdd1016a.png)

**Comment by officialpm** [comment]
> > Fixed!
> > Please check and star the repo if it worked for you? 👍🏻
> 
> @officialpm, Nope, it does not work...
> 
> ![Screenshot_2022-02-14_01-41-14](https://user-images.githubusercontent.com/13188580/153780663-57744551-2469-4d22-9d37-7733fdd1016a.png)

It's working for me, can you share the Slideshare URL? 
Also, the new app url is - https://slideshare.vercel.app

**Comment by Symbian9** [comment]
> It's working for me, can you share the Slideshare URL?

- https://www.slideshare.net/andreasjakl/python-pys60

> Also, the new app url is - https://slideshare.vercel.app

Just tried this one — it shows me message *"Your slides are downloaded!*😍*"*, BUT it does not provide me any download link and not asks me to save file `¯\_(ツ)_/¯`

https://user-images.githubusercontent.com/13188580/153781148-143d72bb-8e9c-4ee0-bd2b-b31930314e51.mp4

**Comment by officialpm** [comment]
> > It's working for me, can you share the Slideshare URL?
> 
> * https://www.slideshare.net/andreasjakl/python-pys60
> 
> > Also, the new app url is - https://slideshare.vercel.app
> 
> Just tried this one — it shows me message _"Your slides are downloaded!_😍_"_, BUT it does not provide me any download link and not asks me to save file `¯\_(ツ)_/¯`
> 
>  slideshare_vercel_app.mp4

Can you check your downloads?

**Comment by Symbian9** [comment]
> Can you check your downloads?

Yes, I checked (it also shown on video and "Download" folder is empty).

Could be download link shown on site instead of showing *"Your slides are downloaded!*😍*"* message?

**Comment by Symbian9** [comment]
> closed this Feb 15, 2022

Why You closed issue? It is still reproducible.
